name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install pytest pytest-cov ruff

      - name: Lint (auto-fix)
        run: |
          ruff check . --fix
          ruff format .
      - name: Lint (verify clean)
        run: ruff check .

      - name: Generate sample data
        env: { PYTHONPATH: src }
        run: python -m sales_etl.cli gen-sample --out data/raw/sales_data.csv --n 200

      - name: Run ETL
        env: { PYTHONPATH: src }
        run: python -m sales_etl.cli etl data/raw/sales_data.csv --out data/processed/sales.parquet

      - name: KPIs smoke test
        env: { PYTHONPATH: src }
        run: python -m sales_etl.cli kpis data/processed/sales.parquet

      - name: Unit tests with coverage
        run: pytest -q --cov=sales_etl --cov-report=xml

      - name: Check coverage file
        run: ls -lah coverage.xml

      - name: Upload coverage to Codecov (public repo)
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          flags: unittests
          verbose: true
          fail_ci_if_error: false

      - name: Upload parquet artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sales-parquet-${{ matrix.python }}
          path: data/processed/sales.parquet
          if-no-files-found: ignore
          retention-days: 7
